# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.4.8
jobs:
  build:
    working_directory: ~/project/ngx-uswds
    docker:
      - image: cimg/node:20.8.0-browsers
    steps:
      - browser-tools/install-chrome
      - checkout
      - run: npm install
      - run: npm run test:components
      - run: npm run build:components
      - run: npm run build:formly
      - store_artifacts:
          path: coverage
          destination: code-coverage
