---
name: ci build

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    lint:
        name: Lint
        runs-on: ubuntu-latest
        permissions:
            contents: read
        steps:
            - name: Check out repository code
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # SHA pin
            - name: Setup Node
              uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # SHA pin
              with:
                  node-version-file: .nvmrc
                  cache: npm
            - name: Install Node Packages
              run: npm ci
            - name: Run lint
              run: npm run lint

    build_and_run_tests:
        name: Build and Run Tests
        runs-on: ubuntu-latest
        permissions:
            contents: read
        steps:
            - name: Check out repository code
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # SHA pin
            - name: Setup Node
              uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # SHA pin
              with:
                  node-version-file: .nvmrc
                  cache: npm
            - name: Install Node Packages
              run: npm ci
            - name: Build the project
              run: |
                npm run build:components \
                && npm run build:formly
            - name: Build Storybook static assets
              run: npm run build-storybook
            - name: Run component tests with coverage
              id: component-tests
              # formly code does not have tests at all; scope coverage to components
              run: npm run test:components
            - name: Upload component coverage artifact
              if: ${{ steps.component-tests.outcome == 'success' }}
              uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
              with:
                  name: uswds-components-coverage
                  path: coverage/uswds-components/**
                  if-no-files-found: error
