name: Deploy to Github Pages
on:
  push:
    branches:
      - main
jobs:
  Build-And-Deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
      - name: Setup Node
        uses: actions/setup-node@f1f314fca9dfce2769ece7d933488f076716723e # v1
        with:
          node-version: "24.x"
      - name: Install Node Packages
        run: npm i
      - name: Build Storybook Assets
        run: npm run build-storybook
      - name: Add .nojekyll file to allow for node_modules to be included in bundle
        run: touch storybook-static/.nojekyll
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@d92aa235d04922e8f08b40ce78cc5442fcfbfa2f # v4.8.0
        with:
          branch: gh-pages
          folder: storybook-static
