name: Deploy to Github Pages
on:
  push:
    branches:
      - main
jobs:
  Build-And-Deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
      - name: Setup Node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: "24.x"
      - name: Install Node Packages
        run: npm i
      - name: Build Storybook Assets
        run: npm run build-storybook
      - name: Add .nojekyll file to allow for node_modules to be included in bundle
        run: touch storybook-static/.nojekyll
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@b36f842fa378d7cbf6695fcac86ecdcef3af8af3 # v4.2.3
        with:
          branch: gh-pages
          folder: storybook-static
